### ISSUE TITLE
Feature Request: API timeout - split the area in smaller ones

### ISSUE THREAD

**Issue by TechG3n** [M4d40/PMSFnestScript#23]
At the moment the overpass querry fails if the area is to big.
If you split it manually you will get different webhooks for each area.

Could the script split the area in smaller ones, querry the api and at the end use the data again as one big area?

**Comment by M4d40** [comment]
we can't just split the area in smaller areas. Each park needs to be completely inside the area given to the api.
And we only know how big each park is, if we get it from the api.
So the only way is, to do it by hand and send the smallest possible area to the api.
Since this is only a problem with multipolygons on some single parks, Just create a simple extra config for that park.
