### ISSUE TITLE
Event Check Fallback

### ISSUE THREAD

**Issue by wrinklytesties** [M4d40/PMSFnestScript#33]
With the most recent event not being updated to the active.json would it possible to return **event_mons** to the wiki, and leave it commented in the config.ini example?

To make it useful, maybe store the last event captured from active.json since nests.py was last run or maybe nests.py check another json url that stores that, to check against the current event found in active.json at the time it's ran.  If it's the same, fallback to using the array found in event_mons.

Idk how feasible this is, just a thought, if it's a bad idea, np.

**Comment by ccev** [comment]
I'm currently working on improving the event source, since other projects are relying on that repo, the fallback should be done within that. I'll probably drop active.json and store event spawns in all.json. This way, the script could also easily take care of e.g. Spotlight Hour spawns, that could otherwise cause problems.
There's also no other source providing machine-readible event data that I know of, else I would have not made my own.

Though, I agree an `event_mons` option in the config should exist.

**Comment by ccev** [comment]
The current pogoinfo repo now stores all events that are ongoing or will start with their Spawns. Nest Watcher will find all events that have been active since the last migration and ignore the spawns. This now also takes care of e.g. community days or spotlight hours that were going on since the last migration.
I think this is enough to close the issue. I see no reason for an event_mons variable in the config now. This should be handled within pogoinfo.
