### ISSUE TITLE
payload too large

### ISSUE THREAD

**Issue by hunch-13** [M4d40/PMSFnestScript#37]
not exactly sure where a map should appear but seeing this

Comparing your bot's emotes to needed nesting mons.
Error while generating Static Map:

https://mysite.uz/staticmap/nests?pregenerate=true&regeneratable=true
{"error":true,"reason":"Payload Too Large"}

Sending a new Nest message 

It DOES post via bot , though not as much as when it was a webhook and there are no maps posted.

**Comment by ccev** [comment]
This is because your Tileserver rejects the map, since - well, the Payload is too large. Nothing I can do. The beta version has a config option to raise payload limits, but I recommend against switching to it right now.

Please try to set "max_markers" in your settings to a lower number. That should make your Payload smaller.

**Comment by hunch-13** [comment]
Set marker to 1 but still no map, not a huge deal and I understand why it gives the error.  A workaround could be only send marker requests when nest over X spawns (config item) perhaps?

**Comment by ccev** [comment]
There already is that option in the discord.json file
